version: "3.7"

services:
  godev:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: godev
    volumes:
      - ./:/go/src/github.com/hohihohi/docker-env/golang
      - ./.netrc:/home/docker/.netrc
    env_file: ./.env
    user: "${UID}:${GID}"
    command: tail -f /dev/null
    ports:
      # 8888 (for web server) and 2345 (for debugger)
      - 8888:8888
      - 2345:2345
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
